cleanly partition pls.h as own dependency
tjhladish/AbcSmc pull request #19
Opened 2023-02-10 10:21 UTC by pearsonca

This change partitions the pls.h functionality as its own dependency, i.e. without any other abcsmc library dependencies.

This has the knock-on effect of moving some definitions from AbcUtil.h to pls.h, namely the linear algebra types, some functions which are used (within AbcSmc, at least - not sure about simulators) exclusively in pls functions, and one function which was used elsewhere (`ordered`).

I think there's an argument to be made for a "PLS" namespace to capture the types, but didn't do that here. I also think there's some argument for moving more of AbcUtil functions to PLS header. Those should be straightforward changes.

Once we've resolved those considerations, the next level step is of course to spin PLS.h off entirely into it's own repository, and then refactor this to depend on that as a library.

2023-02-10 10:34 UTC, pearsonca commented
Also tempted to incorporate this for signum operations: https://stackoverflow.com/a/4609795/167973

2023-02-10 12:38 UTC, pearsonca commented
n.b. there is a [PLS](https://github.com/tjhladish/PLS) library already, and this change moves in the direction of having that as a well-defined dependency (for simplicity, perhaps incorporated as a submodule?)

2023-02-10 17:20 UTC, tjhladish commented on pls.h
> +#include <algorithm> // sort
Pls move includes to top

2023-02-10 17:23 UTC, tjhladish commented on pls.h
> +std::vector<std::size_t> ordered(const T& v)
Standardize whitespace usage (not just here): `ret_type func_name (arg_type arg) {`

2023-03-03 12:30 UTC, tjhladish commented on AbcSim.h
> +      vector<float_type> pars, const unsigned long int seed, const unsigned long int serial, const ABC::MPI_par* _mp
@pearsonca I think we still want the args commented:
```suggestion
      vector<float_type> /*pars*/, const unsigned long int /*seed*/, const unsigned long int /*serial*/, const ABC::MPI_par* /*_mp*/
```

2023-03-03 12:31 UTC, tjhladish commented on AbcSim.h
> +      vector<float_type> pars, const unsigned long int seed, const unsigned long int serial, const ABC::MPI_par* _mp
```suggestion
      vector<float_type> pars, const unsigned long int /*seed*/, const unsigned long int /*serial*/, const ABC::MPI_par* /*_mp*/
```

2023-03-03 13:06 UTC, tjhladish requested changes
See in-line suggested changes

2023-03-03 13:08 UTC, merged